app/posts/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField, TextAreaField, TextField, SelectField, widgets
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from app.models import User
from flask_login import current_user



class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(min=10)])
    content = TextAreaField('Content', validators=[DataRequired()])
    image = FileField('Featured Image', validators=[FileAllowed(['jpg', 'png', 'jpeg'])])
    
    submit = SubmitField('Publish')
    
    
class CommentForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    comment = TextAreaField('Comment', validators=[DataRequired(), Length(min=10)])
    submit = SubmitField('Submit')

app/posts/views.py
import os
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint, current_app)
from flask_login import current_user, login_required, logout_user
from app import db, bcrypt
import secrets
from PIL import Image
from app.request import get_quote
from app.models import Post, User, Comment
from app.posts.forms import PostForm, CommentForm
from app.request import get_quote
from flask_simplemde import SimpleMDE
from ..main import views


posts = Blueprint('posts', __name__)
quotes = get_quote()


def save_picture(form_image):
    randome_hex = secrets.token_hex(8)
    f_name, f_ext = os.path.splitext(form_image.filename)
    picture_name = randome_hex + f_ext
    picture_path = os.path.join(current_app.root_path, 'static/featured_images', picture_name)
    
    output_size = (1000, 400)
    final_image = Image.open(form_image)
    final_image.thumbnail(output_size)
    
    final_image.save(picture_path)
    
    return picture_name


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    
    if form.validate_on_submit():
        pic =None
        if form.image.data:
            picture_file = save_picture(form.image.data)
            final_pic = picture_file
            pic= final_pic
        post = Post(title=form.title.data, content=form.content.data, author=current_user, image=pic)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been published!', 'success')
        return redirect(url_for('main.home'))
    
    myposts = Post.query.order_by(Post.posted_date.desc())
    return render_template('new-post.html', title='New Post', form=form, legend='New Post', myposts=myposts, quotes=quotes)


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    comments = Comment.query.filter_by(post_id = post_id).all()
    myposts = Post.query.order_by(Post.posted_date.desc())
    return render_template('post.html', title=post.title, post=post, comments = comments, myposts=myposts, quotes=quotes)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        if form.image.data:
            picture_file = save_picture(form.image.data)
            final_pic = picture_file
             
             
        post.title = form.title.data
        post.content = form.content.data
    
        post.image = final_pic
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
        
    myposts = Post.query.order_by(Post.posted_date.desc())
    return render_template('new-post.html', title='Update Post', form=form, legend='Update Post', quotes=quotes, myposts=myposts)


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))


@posts.route("/post/<int:post_id>/comment", methods=['GET', 'POST'])
@login_required
def new_comment(post_id):
    post = Post.query.get_or_404(post_id)
    
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(comment=form.comment.data, fullname=form.name.data, author=current_user, post_id = post_id )
        db.session.add(comment)
        db.session.commit()
        # comments = Comment.query.all()
        flash('You comment has been created!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    myposts = Post.query.order_by(Post.posted_date.desc())
    return render_template('new-comment.html', title='New Comment', form=form, legend='New Comment', myposts=myposts, quotes=quotes)


@posts.route('/deleteComment/<int:comment_id>/<int:post_id>', methods=["GET", "POST"])
def deleteComment(comment_id, post_id):
    post = Post.query.get_or_404(post_id)
    
    comment = Comment.query.filter_by(id=comment_id).first()
    db.session.delete(comment)
    db.session.commit()
    return redirect(url_for("posts.post", post_id=post.id))


@posts.route("/comment/<int:id>")
def commentpage(id):
    comments = Comment.query.filter_by(id = id).all()
    return render_template('comment.html', title=Comment, comments = comments)



@posts.route("/comment/<int:comment_id>/delete", methods=['POST'])
@login_required
def comment(coment_id):
    post = Post.query.get_or_404(post_id)
    comments = Comment.query.get_or_404(comment_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(comments)
    db.session.commit()
    flash('The comment has been deleted!', 'success')
    return redirect(url_for('posts.post', comment_id=comment.id))


@posts.route('/quote')
def getquotes():

    quotes = get_quote()
    # title = name
    
    return render_template('layout.html', quotes=quotes)
import os
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint, current_app)
from flask_login import current_user, login_required, logout_user
from app import db, bcrypt
import secrets
from PIL import Image
from app.request import get_quote
from app.models import Post, User, Comment
from app.posts.forms import PostForm, CommentForm
from app.request import get_quote
from flask_simplemde import SimpleMDE
from ..main import views


posts = Blueprint('posts', __name__)
quotes = get_quote()


def save_picture(form_image):
    randome_hex = secrets.token_hex(8)
    f_name, f_ext = os.path.splitext(form_image.filename)
    picture_name = randome_hex + f_ext
    picture_path = os.path.join(current_app.root_path, 'static/featured_images', picture_name)
    
    output_size = (1000, 400)
    final_image = Image.open(form_image)
    final_image.thumbnail(output_size)
    
    final_image.save(picture_path)
    
    return picture_name


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    
    if form.validate_on_submit():
        pic =None
        if form.image.data:
            picture_file = save_picture(form.image.data)
            final_pic = picture_file
            pic= final_pic
        post = Post(title=form.title.data, content=form.content.data, author=current_user, image=pic)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been published!', 'success')
        return redirect(url_for('main.home'))
    
    myposts = Post.query.order_by(Post.posted_date.desc())
    return render_template('new-post.html', title='New Post', form=form, legend='New Post', myposts=myposts, quotes=quotes)


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    comments = Comment.query.filter_by(post_id = post_id).all()
    myposts = Post.query.order_by(Post.posted_date.desc())
    return render_template('post.html', title=post.title, post=post, comments = comments, myposts=myposts, quotes=quotes)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        if form.image.data:
            picture_file = save_picture(form.image.data)
            final_pic = picture_file
             
             
        post.title = form.title.data
        post.content = form.content.data
        post.category = form.category.data
        post.image = final_pic
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
        form.category.data = post.category
    myposts = Post.query.order_by(Post.posted_date.desc())
    return render_template('new-post.html', title='Update Post', form=form, legend='Update Post', quotes=quotes, myposts=myposts)


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))


@posts.route("/post/<string:category>")
def category_post(category):
    post = Post.query.filter_by(category=category).all()
    print("..............", post)
    myposts = Post.query.order_by(Post.posted_date.desc())
    return render_template('category.html', post=post, category=category, myposts=myposts, quotes=quotes) 


@posts.route("/post/<int:post_id>/comment", methods=['GET', 'POST'])
@login_required
def new_comment(post_id):
    post = Post.query.get_or_404(post_id)
    
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(comment=form.comment.data, fullname=form.name.data, author=current_user, post_id = post_id )
        db.session.add(comment)
        db.session.commit()
        # comments = Comment.query.all()
        flash('You comment has been created!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    myposts = Post.query.order_by(Post.posted_date.desc())
    return render_template('new-comment.html', title='New Comment', form=form, legend='New Comment', myposts=myposts, quotes=quotes)


@posts.route('/deleteComment/<int:comment_id>/<int:post_id>', methods=["GET", "POST"])

app/users/views.py
import os
from .. import mail
from flask import render_template, url_for, flash, redirect, request, Blueprint, url_for, current_app
from flask_login import login_user, current_user, logout_user, login_required
from app import db, bcrypt
from app.models import User, Post, Comment
from app.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm)
import secrets
from PIL import Image
from flask_mail import Message
from ..email import mail_message
from app.request import get_quote

# from app import mail

users = Blueprint('users', __name__)
quotes = get_quote()


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, fullname=form.fullname.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
                
        flash('Your account has been created! You are now able to log in', 'success')
        # mail_message("Welcome to FLASK BLOG","email/welcome_user",user.email,user=user)

        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form, quotes=quotes)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form, quotes=quotes)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


def save_picture(form_picture):
    randome_hex = secrets.token_hex(8)
    f_name, f_ext = os.path.splitext(form_picture.filename)
    picture_name = randome_hex + f_ext
    picture_path = os.path.join(current_app.root_path, 'static/profile_pics', picture_name)
    
    output_size = (125, 125)
    final_image = Image.open(form_picture)
    final_image.thumbnail(output_size)
    
    final_image.save(picture_path)
    image_files = url_for('static', filename='profile_pics/' + current_user.image)
    return picture_name
    
    
@users.route("/account",  methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image = picture_file
            
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.fullname = form.fullname.data
        current_user.bio = form.bio.data
        current_user.facebook = form.facebook.data
        current_user.twitter = form.twitter.data
        current_user.github = form.github.data
        current_user.linkedin = form.linkedin.data
        db.session.commit()
        
        flash('Your account has been updated.', 'success')
        return redirect(url_for('users.account'))
    
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.fullname.data = current_user.fullname
        form.bio.data = current_user.bio
        form.facebook.data = current_user.facebook
        form.twitter.data = current_user.twitter
        form.github.data = current_user.github
        form.linkedin.data = current_user.linkedin
    
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=current_user.username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.posted_date.desc()).all()
    print('--------', posts)
    myposts = Post.query.order_by(Post.posted_date.desc())
    image_file = url_for('static', filename='profile_pics/' + current_user.image)
    return render_template('account.html', title='Account', posts=posts, user=user, image_file=image_file, form=form, myposts=myposts, quotes=quotes)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.posted_date.desc()).paginate(page=page, per_page=7)
    myposts = Post.query.order_by(Post.posted_date.desc())
    return render_template('userposts.html', posts=posts, user=user, myposts=myposts, quotes=quotes)

app/templates/about.html
{% extends "layout.html" %}

{% block content%} 
<div class="mt-4 pt-4">
    <h1>About Person BLOG</h1>
    <p>Person provide you with the opportunity to share your views with the world. </p>
    <p>This is a blog Powered blogging platform. </p>
</div>
{% endblock content %}

app/templates/comment.html
{% extends "layout.html" %}

{% block content%} 
    <div class="content-section">

        <div class="mt-4 mb-4">

                <h2>Comments</h2>
                <hr>
                {% if comments %}
                {% for comment in comments %}

                

                <ul>
                    <li><h4> {{ comment.comment }} </h4>
                </ul>
                <div>
                    <button type="button" class="btn btn-danger btn-sm m-1 mb-1"  data-toggle="modal" data-target="#deleteComment">Delete</button>
                </div>
                {% endfor %}
           </div>
                            
            {% else %}
                <p>No comments</p>
            {% endif %}
            </div>
    </div>


        <!-- Modal -->
  <div class="modal fade" id="deleteComment" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Comment?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.comment', comment_id=comment_id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
    </div>

{% endblock content %}

app/templates/error404.html
{% extends 'layout.html'%}

{% block content %}
<div class="text-center jumbotron mt-4 pt-2">
        <h2 class="mt-4">WHOOOPS we can't find that page</h2>
        <p>Check to make sure that the URL is correct. Sawa Sawa</p>

</div>
    
{% endblock %}

app/templates/index.html
{% extends "layout.html" %}

{% block jumbo%}
<!-- <div class="mt-4 pt-2"></div> -->
{% endblock %}

{% block content%} 

  <!-- Section heading -->
  <h2 class="h1-responsive font-weight-bold text-center my-2">Recent posts</h2>
  <!-- Grid row -->
    {% for post in posts.items %}

  <!-- Section: Blog v.3 -->
<section class="my-5">

  <div class="row">

    <!-- Grid column -->
    <div class="col-lg-5 col-xl-4">

      <!-- Featured image -->
      <div class="view overlay rounded z-depth-2 mb-lg-0 mb-4">
        {% if post.image %}
        <img class="img-fluid" src="{{ url_for('static', filename='featured_images/')}}{{post.image}}" alt="{{post.title}} image">
        {% else %}
        <img class="img-fluid" src="{{ url_for('static', filename='featured_images/')}}default.jpg" alt="{{post.title}} image">
        {% endif %}
        <a>
          <div class="mask rgba-white-slight"></div>
        </a>
      </div>

    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="col-lg-7 col-xl-8">
      <!-- Post title -->
      <h3><a class="font-weight-bold mb-3 black-text" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h3>
      <!-- Excerpt -->
      <p class="dark-grey-text">{{ post.content | truncate(400) }}</p>
      <!-- Post data -->
      <p>by <a class="font-weight-bold green-text" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.fullname }}</a>, {{ post.posted_date.strftime('%Y - %m - %d') }} 
      </p>
      <!-- Read more button -->
      <a class="btn success-color-dark text-white btn-md" href="{{ url_for('posts.post', post_id=post.id) }}">Read more</a>

    </div>
    <!-- Grid column -->

  </div>
  <!-- Grid row -->

  <hr class="my-5">

  

</section>
<!-- Section: Blog v.3 -->

    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
      <a class="btn btn-sm btn-success mb-2 mt-2" href="{{ url_for('main.home', page=page_num) }}"> {{page_num}} </a>
        {% else %}
        <a class="btn btn-sm btn-outline-success mb-2 mt-2" href="{{ url_for('main.home', page=page_num) }}"> {{page_num}} </a>
        {% endif %}

      {% else %}
        ...
      {% endif %}

    {% endfor %}


    <div class="quotes">

      <!-- <p> {{quotes.quote}}</p>
      <p> {{quotes.author}}</p>                 -->

  </div>

{% endblock content %}

app/templates/navbar.html
 
<!-- <header class="site-header"> -->
        <nav class="navbar navbar-expand-lg navbar-dark primary-color-dark fixed-top">
            <div class="container">
            <a class="navbar-brand mr-4" href="/">BLOG APP</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                <a class="nav-item active nav-link" href="/">Home</a>
                <a class="nav-item nav-link" href="/about">About</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">My Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                {% endif %}
                </div>
            </div>
            </div>
            </nav>
            <!-- </header> -->

app/templates/post.html
 
{% extends "layout.html" %}

{% block content%} 

    <article class="media content-section mt-2 pt-2">
      <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image) }}" alt="{{ post.author.username }} profile photo">
            <div class="media-body">
              <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.fullname }}</a>
                <small class="text-muted mr-2">{{ post.posted_date.strftime('%Y-%m-%d') }}</small>
                <small>Posted in: <a class="mr-2" href="{{ url_for('posts.category_post', category=post.category) }}">{{ post.category }}</a></small>

                {% if post.author == current_user%}
                <div>
                    <a class="btn btn-default btn-sm mt-2 mb-2" href="{{ url_for('posts.update_post', post_id=post.id) }}">Edit</a>
                    <button type="button" class="btn btn-danger btn-sm m-1 mb-1"  data-toggle="modal" data-target="#deleteModal">Delete</button>
                </div>

                {% endif %}
              </div>
              <h2 class="article-title mt-2 pb-2 pt-2 font-weight-bold">{{ post.title }}</h2>

              {% if post.image %}
                <img class="img-fluid" src="{{ url_for('static', filename='featured_images/')}}{{post.image}}" alt="{{post.title}} image">
                {% else %}
                <img class="img-fluid" src="{{ url_for('static', filename='featured_images/')}}default.jpg" alt="{{post.title}} image">
              {% endif %}

              <p class="article-content pt-2 mt-2">{{ post.content }}

                            <!-- Section: Share buttons -->
            <section class="text-center mb-4 smooth-scroll social-buttons">

                <hr>
  
                <p class="font-weight-bold">Spreed the word: </p>
  
                <!--Facebook-->
                <button type="button" class="btn btn-sm btn-info my-0">
                  <i class="fab fa-facebook-f"></i>
                </button>
  
                <!--Twitter-->
                <button type="button" class="btn btn-sm btn-info my-0">
                  <i class="fab fa-twitter"></i>
                </button>
  
                <!--Twitter-->
                <button type="button" class="btn btn-sm btn-info my-0">
                  <i class="fab fa-linkedin-in"></i>
                </button>
  
                <!-- Comments -->
                <a role="button" class="btn btn-sm btn-unique my-0 mt-xs-4" href="#comments">
                  <i class="far fa-comments mr-1"></i> Add comment
                </a>
  
                <hr>
  
              </section>
              <!-- Section: Share buttons -->
              </p>
            </div>
            </article>

            <!--Section: Author Box-->
            <section class="mb-4 content-section">

                <div class="text-center font-weight-bold">About the author</div>
  
                <div class="media mt-4 px-1">
                  <img class="card-img-100 rounded d-flex z-depth-1 mr-3"
                    src="{{ url_for('static', filename='profile_pics/' + post.author.image) }}" alt="Generic placeholder image">
                  <div class="media-body">
  
                    <div class="d-block">
                      <p class="font-weight-bold my-0">
                        <a href="" class="black-text">{{ post.author.fullname }}</a>
                      </p>
                      <div class="my-2">
                        <a class="mr-1" role="button" href="{{ post.author.facebook}}" target="_blank"><i class="fab  fa-facebook-f"></i></a>
                        <a class="mr-1" role="button" href="{{ post.author.twitter }}" target="_blank"><i class="fab fa-twitter"></i></a>
                        <a class="mr-1" role="button" href="{{ post.author.github }}" target="_blank"><i class="fab fa-github"></i></a>
                        <a class="mr-1" role="button" href="{{ post.author.linkedin }}" target="_blank"><i class="fab fa-linkedin-in"></i></a>
                      </div>
                    </div>
  
                    <p>{{post.author.bio}}</p>
                  </div>
                </div>
  
              </section>
              <!--Section: Author Box-->

    <div class="content-section">
        <a class="ratings font-weight-bold" href="{{ url_for('posts.new_comment', post_id=post.id) }}"> Write a comment</a>

        <div class="mt-4 mb-4" id="comments">

                <h2>Comments</h2>
                <hr>
                {% if comments %}
                {% for comment in comments %}

                <ul>
                    <p>Posted by: {{comment.author.username}}</p>
                    <h4> {{ comment.comment }} </h4>
                </ul>
                {%if current_user.is_authenticated and current_user.id == post.user_id %}
                <a href="{{url_for('posts.deleteComment', comment_id=comment.id, post_id=post.id)}}"><button class="btn btn-danger btn-sm m-1 mb-1">Delete</button></a>
                {%endif%}
            {% endfor %} 
            {% else %}
                <p>No comments</p>
            {% endif %}
            </div>
    </div>
   <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
              </form>
            </div>
          </div>
        </div>
        </div>

{% endblock content %}

app/templates/subsribe.html
{% extends "layout.html" %}

{% block content%} 
<div class="mt-4 pt-4">
    <h1>You are Subscribed</h1>
    <p>Thank you for Subscribing to Flask blog, you will get now get updates when we publish new articles. </p>
</div>
{% endblock content %}

app/templates/userposts.html
 
{% extends "layout.html" %}

{% block content%} 
    <h2 class="mb-4 mt-4 pt-2"> {{ posts.total }} Posts by {{user.fullname}} </h2>

    {% for post in posts.items %}

     <!-- Section: Blog v.3 -->
<section class="my-5">

    <div class="row">
  
      <!-- Grid column -->
      <div class="col-lg-5 col-xl-4">
  
        <!-- Featured image -->
        <div class="view overlay rounded z-depth-2 mb-lg-0 mb-4">
            {% if post.image %}
            <img class="img-fluid" src="{{ url_for('static', filename='featured_images/')}}{{post.image}}" alt="{{post.title}} image">
            {% else %}
            <img class="img-fluid" src="{{ url_for('static', filename='featured_images/')}}default.jpg" alt="{{post.title}} image">
            {% endif %}
          <a>
            <div class="mask rgba-white-slight"></div>
          </a>
        </div>
  
      </div>
      <!-- Grid column -->
  
      <!-- Grid column -->
      <div class="col-lg-7 col-xl-8">
        <!-- Post title -->
        <h3><a class="font-weight-bold mb-3 black-text" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h3>
        <!-- Excerpt -->
        <p class="dark-grey-text">{{ post.content | truncate(400) }}</p>
        <!-- Post data -->
        <p>by <a class="font-weight-bold" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.fullname }}</a>, {{ post.posted_date.strftime('%Y-%m-%d') }} 
          <span class="ml-4"></span> Category: <a href="{{ url_for('posts.category_post', category=post.category) }}" class="green-text">
           <span class="font-weight-bold mb-3"> {{ post.category }}</span>
        </p>
        <!-- Read more button -->
        <a class="btn success-color-dark text-white btn-md" href="{{ url_for('posts.post', post_id=post.id) }}">Read more</a>
  
      </div>
      <!-- Grid column -->
  
    </div>
    <!-- Grid row -->
  
    <hr class="my-5">
  
  </section>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
      <a class="btn btn-sm btn-success mb-2 mt-2" href="{{ url_for('users.user_posts', username = user.username, page=page_num) }}"> {{page_num}} </a>
        {% else %}
        <a class="btn btn-sm btn-outline-success mb-2 mt-2" href="{{ url_for('users.user_posts', username = user.username, page=page_num) }}"> {{page_num}} </a>
        {% endif %}

      {% else %}
        ...
      {% endif %}

    {% endfor %}

{% endblock content %}